### ISSUE TITLE
error with playsound

### ISSUE THREAD

**Issue by Hello11230029** [lnxcz/discord-sniper#65]
i get this error, but i installed the requirements and also tried to do it manually

Traceback (most recent call last):
  File "C:\Users\dddd\OneDrive\Desktop\tools\discord-sniper-master\discord-sniper-master\main.py", line 10, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'

**Comment by lnxcz** [comment]
it probably isn't listed in the requirements file. Try to just install it separately: `pip install playsound`

**Comment by lnxcz** [comment]
did you install the requirements?

**Comment by lnxcz** [comment]
i was unable to replicate this issue, however my recommendation would be to try moving the folder outside of the OneDrive folder, or to reinstall Python and make sure it is registered in the path

**Comment by lnxcz** [comment]
or refer to https://github.com/lnxcz/discord-sniper/issues/64#issuecomment-1664190018
